# [START app_yaml]
runtime: nodejs
env: flex

# [START env]
env_variables:
  NODE_ENV: production
  INSTANCE_CONNECTION_NAME: ugwo-platform:us-central1:ugwo-sql-001
# [END env]

# [START cloudsql_settings]
beta_settings:
  # The connection name of your instance, available by using
  # 'gcloud beta sql instances describe [INSTANCE_NAME]' or from
  # the Instance details page in the Google Cloud Platform Console.
  cloud_sql_instances: ugwo-platform:us-central1:ugwo-sql-001
# [END cloudsql_settings]
# [END app_yaml]