-----BEGIN PRIVATE KEY-----
MIGTAgEAMBMGByqGSM49AgEGCCqGSM49AwEHBHkwdwIBAQQgm3vnrJOQCwPVHH//sokjVb0xGrQd/xslaqwRuQ4psg2gCgYIKoZIzj0DAQehRANCAAStMXE36DJrkqbgNvnfPKbXGA4pUU2ijlt/N3aGiEhDdiV6BlVqZ+5YPu2RKtgmtPgZyaRNpWq/AhGBxG+A8beZ
-----END PRIVATE KEY-----